replicaCount: 1

image:
  repository: wallabag/wallabag
  tag: "2.6.13"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: wallabag.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 8Gi

postgresql:
  enabled: true
  auth:
    postgresPassword: "changeme"
    username: "wallabag"
    password: "wallabag_password"
    database: "wallabag"

redis:
  enabled: true
  auth:
    enabled: false

wallabag:
  domainName: "http://wallabag.local"
  serverName: "Wallabag"
  locale: "en"
  fosUserRegistration: false
  fosUserConfirmation: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
