apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wallabag.fullname" . }}
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
data:
  SYMFONY__ENV__DOMAIN_NAME: {{ .Values.wallabag.domainName | quote }}
  SYMFONY__ENV__SERVER_NAME: {{ .Values.wallabag.serverName | quote }}
  SYMFONY__ENV__FOSUSER_REGISTRATION: {{ ternary "true" "false" .Values.wallabag.fosUserRegistration | quote }}
  SYMFONY__ENV__TWOFACTOR_AUTH: {{ ternary "true" "false" .Values.wallabag.twoFactorAuth | quote }}
  SYMFONY__ENV__FROM_EMAIL: {{ .Values.wallabag.fromEmail | quote }}
  SYMFONY__ENV__SECRET: {{ .Values.wallabag.secret | quote }}

  SYMFONY__ENV__DATABASE_DRIVER: {{ (eq .Values.database.type "postgresql" | ternary "pdo_pgsql" "pdo_mysql") | quote }}
  SYMFONY__ENV__DATABASE_HOST: {{ .Values.database.host | quote }}
  SYMFONY__ENV__DATABASE_PORT: {{ .Values.database.port | quote }}
  SYMFONY__ENV__DATABASE_NAME: {{ .Values.database.name | quote }}
  SYMFONY__ENV__DATABASE_USER: {{ .Values.database.user | quote }}
