{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallabag.databaseSecretName" . }}
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.database.secretPasswordKey }}: {{ randAlphaNum 32 | b64enc }}
{{- end }}
