{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | default "wallabag" }}
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
    environment: {{ .Values.namespace.environment | default "production" }}
    app: {{ .Values.namespace.app | default "wallabag" }}
{{- end }}
