apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallabag.fullname" . }}-secret
  labels:
    {{- include "wallabag.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.postgresql.auth.password | b64enc }}
